language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - RUN_TESTS=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: RUN_CS=1 RUN_TESTS=0

    - php: 7.0
      env: RUN_COVERAGE=1 RUN_TESTS=0 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

before_script:
  - phpenv config-rm xdebug.ini

  - composer self-update

  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --prefer-dist --no-interaction

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"

script:
  - sh -c "if [ '$RUN_TESTS' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$RUN_CS' = '1' ]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"

  - sh -c "if [ '$RUN_COVERAGE' = '1' ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml || true; fi"
  - sh -c "if [ '$RUN_COVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
  - sh -c "if [ '$RUN_COVERAGE' = '1' ]; then bash codecov.sh; fi"

notifications:
  email: false
